server:
  motd: "&-Freedom ยง8- &-1.7 - %mcversion%"
  staffmode: false
discord:
  token: ""
  guild-id: ""
  channels:
    console-id: ""
    chat-id: ""
mysql:
  enabled: false #Will enable SQLite if false
  username: ""
  password: ""
  database: ""
  host: ""
  port: 3306